 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
 spec:
   replicas: 1
   template:
     metadata:
       name: k8s-bigip-ctlr
       labels:
         app: k8s-bigip-ctlr
     spec:
       # Name of the Service Account bound to a Cluster Role with the required
       # permissions
       serviceAccountName: bigip-ctlr
       containers:
         - name: k8s-bigip-ctlr
           image: "snatra27/cis-k8s-ctlr-biq-as3:1.0"
           env:
             - name: BIGIP_USERNAME
               valueFrom:
                 secretKeyRef:
                   # Replace with the name of the Secret containing your login
                   # credentials
                   name: bigip-login
                   key: username
             - name: BIGIP_PASSWORD
               valueFrom:
                 secretKeyRef:
                   # Replace with the name of the Secret containing your login
                   # credentials
                   name: bigip-login
                   key: password
             - name: BIGIQ_USERNAME
               valueFrom:
                 secretKeyRef:
                   # Replace with the name of the Secret containing your login
                   # credentials
                   name: bigiq-login
                   key: username
             - name: BIGIQ_PASSWORD
               valueFrom:
                 secretKeyRef:
                   # Replace with the name of the Secret containing your login
                   # credentials
                   name: bigiq-login
                   key: password
           command: ["/app/bin/k8s-bigip-ctlr"]
           args: [
             # BIG IP Configs
             "--bigip-username=$(BIGIP_USERNAME)",
             "--bigip-password=$(BIGIP_PASSWORD)",
             "--bigip-url=10.192.75.98",
             # BIG IQ Configs
             "--bigiq-mode=true",
             "--bigip-username=$(BIGIQ_USERNAME)",
             "--bigip-password=$(BIGIQ_PASSWORD)",
             "--bigiq-url=https://10.192.75.180/",
             "--bigip-partition=k8s",
             "--pool-member-type=cluster",
             # Replace with the path to the BIG-IP VXLAN connected to the
             "--flannel-name=fl-vxlan",
             # Self-signed cert
             "--insecure=true",
             "--agent=as3",
            ]