apiVersion: v1
kind: ClusterRole
metadata:
    annotations:
        authorization.openshift.io/system-only: 'true'
    name: 'system:bigip-ctlr'
rules:
    -
        apiGroups:
            - ""
            - extensions
        resources:
            - nodes
            - services
            - endpoints
            - namespaces
            - ingresses
            - routes
        verbs:
            - get
            - list
            - watch
    -
        apiGroups:
            - ""
            - extensions
        resources:
            - configmaps
            - events
            - ingresses/status
        verbs:
            - get
            - list
            - watch
            - update
            - create
            - patch
    -
        apiGroups:
            - ""
            - extensions
        resources:
            - secrets
        resourceNames:
            - '<secret-containing-bigip-login>'
        verbs:
            - get
            - list
            - watch
userNames:
    - 'system:serviceaccount:kube-system:bigip-ctlr'
subjects:
    -
        kind: ServiceAccount
        name: bigip-ctlr
roleRef:
    name: 'system:bigip-ctlr'